name: Central Market Web Mobile CI/CD

on:
  push:
    branches:
      - sidof-dev

  pull_request:
    branches:
      - main
      - deployment
      - test

jobs:
  build-deploy:
    name: Build and Deploy Web App
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build application
      - name: Build the app
        run: npm run build --if-present

      # Docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build & Push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/central-market-web:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/central-market-web:${{ github.sha }}
